In [2]:
from google.colab import files

print("Please select the 'marketing_campaign.csv' file to upload:")
uploaded = files.upload()

Please select the 'marketing_campaign.csv' file to upload:

Saving marketing_campaign.csv to marketing_campaign.csv

In [6]:
import pandas as pd
df = pd.read_csv("marketing_campaign.csv", sep="\t")
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [7]:
df.isnull().sum() #missing values

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [13]:
df = df.drop_duplicates() # Remove duplicates
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent)

id                     0.0
year_birth             0.0
education              0.0
marital_status         0.0
income                 0.0
kidhome                0.0
teenhome               0.0
dt_customer            0.0
recency                0.0
mntwines               0.0
mntfruits              0.0
mntmeatproducts        0.0
mntfishproducts        0.0
mntsweetproducts       0.0
mntgoldprods           0.0
numdealspurchases      0.0
numwebpurchases        0.0
numcatalogpurchases    0.0
numstorepurchases      0.0
numwebvisitsmonth      0.0
acceptedcmp3           0.0
acceptedcmp4           0.0
acceptedcmp5           0.0
acceptedcmp1           0.0
acceptedcmp2           0.0
complain               0.0
z_costcontact          0.0
z_revenue              0.0
response               0.0
dtype: float64

In [18]:
df["z_revenue"] = df["z_revenue"].fillna(df["z_revenue"].median())

In [19]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [id, year_birth, education, marital_status, income, kidhome, teenhome, dt_customer, recency, mntwines, mntfruits, mntmeatproducts, mntfishproducts, mntsweetproducts, mntgoldprods, numdealspurchases, numwebpurchases, numcatalogpurchases, numstorepurchases, numwebvisitsmonth, acceptedcmp3, acceptedcmp4, acceptedcmp5, acceptedcmp1, acceptedcmp2, complain, z_costcontact, z_revenue, response]
Index: []

[0 rows x 29 columns]

In [23]:
df.columns = df.columns.str.strip()
df["education"] = df["education"].str.strip()

In [26]:
df['marital_status'] = df['marital_status'].replace({
    'Absurd': 'Absurd',
    'Yolo': 'Yolo',
    'Together': 'Together',
    'Divorced': 'Divorced'
})

In [27]:
print(df['marital_status'].unique())

['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'Yolo']

In [29]:
Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["income"] < lower) | (df["income"] > upper)]

print(outliers)

         id  year_birth   education marital_status  income  kidhome  teenhome  \
164    8475        1973         Phd        Married  157243        0         1
617    1503        1976         Phd       Together  162397        1         1
655    5555        1975  Graduation       Divorced  153924        0         0
687    1501        1982         Phd        Married  160803        0         0
1300   5336        1971      Master       Together  157733        1         0
1653   4931        1977  Graduation       Together  157146        0         0
2132  11181        1949         Phd        Married  156924        0         0
2233   9432        1977  Graduation       Together  666666        1         0

     dt_customer  recency  mntwines  ...  numwebvisitsmonth  acceptedcmp3  \
164   2014-03-01       98        20  ...                  0             0
617   2013-06-03       31        85  ...                  1             0
655   2014-02-07       81         1  ...                  0             0
687   2012-08-04       21        55  ...                  0             0
1300  2013-06-04       37        39  ...                  1             0
1653  2013-04-29       13         1  ...                  1             0
2132  2013-08-29       85         2  ...                  0             0
2233  2013-06-02       23         9  ...                  6             0

      acceptedcmp4  acceptedcmp5  acceptedcmp1  acceptedcmp2  complain  \
164              0             0             0             0         0
617              0             0             0             0         0
655              0             0             0             0         0
687              0             0             0             0         0
1300             0             0             0             0         0
1653             0             0             0             0         0
2132             0             0             0             0         0
2233             0             0             0             0         0

      z_costcontact  z_revenue  response
164               3         11         0
617               3         11         0
655               3         11         0
687               3         11         0
1300              3         11         0
1653              3         11         0
2132              3         11         0
2233              3         11         0

[8 rows x 29 columns]

In [9]:
df.columns = df.columns.str.lower().str.replace(" ", "_") # Rename columns

In [10]:
df['dt_customer'] = pd.to_datetime(df['dt_customer'], dayfirst=True) # Convert date column

In [11]:
df['education'] = df['education'].str.title()
df['marital_status'] = df['marital_status'].str.title() # Standardize text columns

In [12]:
df['income'] = df['income'].fillna(df['income'].median()).astype(int) # Fix data types

In [31]:
df.sort_values(by="id", ascending=False, inplace=True)

In [32]:
df.head()

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
341,11191,1986,Graduation,Divorced,41411,0,0,2013-12-07,11,37,...,6,0,0,0,0,0,0,3,11,0
997,11188,1957,Graduation,Together,26091,1,1,2014-02-25,84,15,...,5,0,0,0,0,0,0,3,11,0
2183,11187,1978,Basic,Single,26487,1,0,2013-05-20,23,2,...,5,0,0,0,0,0,0,3,11,0
2132,11181,1949,Phd,Married,156924,0,0,2013-08-29,85,2,...,0,0,0,0,0,0,0,3,11,0
93,11178,1972,Master,Single,42394,1,0,2014-03-23,69,15,...,7,0,0,0,0,0,0,3,11,0

After uploading, you can now run the cell `OuyQv6xxFfk6` again to load and clean the dataset.